"""cambiar role a enum

Revision ID: 7d3f5904f28a
Revises: 44b306fdc900
Create Date: 2025-05-29 15:23:43.977287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d3f5904f28a'
down_revision = '44b306fdc900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'VISITOR', 'JANITOR', 'MODERATOR', 'ADMINISTRATOR', name='userrole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('PENDING', 'VISITOR', 'JANITOR', 'MODERATOR', 'ADMINISTRATOR', name='userrole'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
